### ISSUE TITLE
Running on multiple A100s

### ISSUE THREAD

**Issue by dasantonym** [tud-zih-energy/FIRESTARTER#36] opened 2022-02-23 10:16 UTC
I tried to run the prebuilt CUDA 11 binary on an Ubuntu 20.04 system with Cuda 11.6 and eight A100 GPUs.

When it gets to the GPUs, the following error occurs:

```
﻿﻿  graphics processor characteristics:
Error: CUBLAS error at /home/runner/work/FIRESTARTER/FIRESTARTER/src/firestarter/Cuda/Cuda.cpp:311: error code = 1 (CUBLAS_STATUS_NOT_INITIALIZED), device index: 7
Error: CUBLAS error at /home/runner/work/FIRESTARTER/FIRESTARTER/src/firestarter/Cuda/Cuda.cpp:311: error code = 1 (CUBLAS_STATUS_NOT_INITIALIZED), device index: 2
Error: CUBLAS error at /home/runner/work/FIRESTARTER/FIRESTARTER/src/firestarter/Cuda/Cuda.cpp:311: error code = 1 (CUBLAS_STATUS_NOT_INITIALIZED), device index: 3
Error: CUBLAS error at /home/runner/work/FIRESTARTER/FIRESTARTER/src/firestarter/Cuda/Cuda.cpp:311: error code = 1 (CUBLAS_STATUS_NOT_INITIALIZED), device index: 4
Error: CUBLAS error at /home/runner/work/FIRESTARTER/FIRESTARTER/src/firestarter/Cuda/Cuda.cpp:311: error code = 1 (CUBLAS_STATUS_NOT_INITIALIZED), device index: 5
Error: CUBLAS error at /home/runner/work/FIRESTARTER/FIRESTARTER/src/firestarter/Cuda/Cuda.cpp:311: error code = 1 (CUBLAS_STATUS_NOT_INITIALIZED), device index: 6
Segmentation fault (core dumped)
```

There seems to be no error for device 1. `nvidia-smi` reports all eight GPUs normally.

**Comment by dasantonym** [comment] 2022-02-23 13:42
After further review, I don't see how this would be related to Firestarter. More likely something with our setup, sorry!

**Comment by dasantonym** [comment] 2022-02-25 15:21
Actually, it was not the setup. gpu_burn worked fine and everything looks normal.

**Comment by rschoene** [comment] 2022-02-28 07:09
I currently can't reproduce it on our A100 system with CUDA 11.1 installed. We will have a more detailed look at the issue. Sorry for the inconvenience.

**Comment by rschoene** [comment] 2022-03-01 11:56
I now also tried it with CUDA 11.6 on our A100 partition and still cannot reproduce your problem. Could you list the output of
```
ldd ./FIRESTARTER_CUDA_11.0
```
? Thanks.

**Comment by rschoene** [comment] 2024-06-27 09:33
@dasantonym Could you check whether this persists, if we do not hear back, we will close the issue.

**Comment by rschoene** [comment] 2024-08-22 06:45
Closed due to no feedback. Maybe fixed with update.

**Closed by rschoene** 2024-08-22 06:45 UTC
